spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hydroblok/hbmall/
          searchPaths: config/*
        #native:
        #  search-locations: classpath:/shared
  #profiles:
  #  active: native
  security:
    user:
      name: ${CONFIG_SERVICE_USER}
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

