sudo: required
services:
- docker
language: java
jdk: oraclejdk8
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: Qt4KXj3Pf3HhhreWl8NufJKBVz81a5QTlfoEJhUm1Wn2ZrZEFWymH5DMx84MDA6beTWNVsDWTqPmHl+WpMtv2yBvCOByWkiUOqFCO9Z/1meLHm2nxswPfbT4eJdr2Ksil+hP6vG62uzJfwbPrad9gKn8SO4mnLENz9QVUVfNS6jZ/hB/eJKN9IK8boorc+5xeGcHqPFGdWvdcaRavE0ugFW6frd0GswrV5DrEY22I6kyTUPlT0KLgkfwdSsVRq4XigJnXo0YHzcaOdHXZvPwa1Yo/nr8O2xhWLLQ4GlFU/LLu2FcPcS5VDHSbiGzz41jQs7Y66lYgNQeWYXvJbTXYmNbgeTH3OLhijS2oPXjw4wv5LehgMM39zMEFEIcwbHDFCCk5jBjiNTMWaoHs+xq2oPqjVm98n488cY5Wg3X40vo9yDxbUNA78fABLQnVYixCI0wDUGe0GpDnTSkVC+EMiOaEPE72JXMqbV7xyLXI3pqwJjN81dr/LTvgR7adTCtikFS5qRroWuR6ZndOgNNO80ng6cVHeyobFOtxhLAISE7zzPlV6B/LHyPx3ymg6juPT+fkOG89ZQe/a5I2goeFEWkSAtSEEJeGaOsxlesQiWO0qZG/P3AbV/Y7qszMYiANj2rdN9RwLqM3f0fz5lOWGr+3kBjznHtqErZ9J5PRRA=
  - secure: Z/TVrVfLo2pwsiprgdYo9/frJBgnnoQuanDW8hPk1EAGu7YJxP7OT8VmhR9J0f9KGDlNDR0Ye6c4iHD1unatIbnS75NJWldLWLZX0kqitb9mfYDdCPUNEQOE7En9pVofY+Cd896duTGeyH+pvjaxB4EHOeXwsyWzi99amhuVLWOZ4BWSwF58hNyNhX/R3QVee3OWbfL1u3sR0IcDgbJIpQc5um0KYnxec/H7+hlaidVFTySDhWy3CzUMup0cJ3z+57jTyKV9U+3iAE7MF1c0ottL816gAJiect/hefxE8dV5lqPfdNKM2hPgcDRLR5SvLlp/QocDm6naXmjbQCr5vfLseO1fpiiGybr7hu3GX2AqHMHgvUQe4y451RhT1dNACTC+UZlDEgbP+VRcOS7+oxNxtoXlQb6nVsqRoq9b4OO5vO5ZcmvWzAzidmiSCo537R3WHSi+nzYKCzGP1yOnErpHZ+4M2DxPzEABvuSKO0E87pfcx56kERPLUgKJd+iLUTA4CH3DALXyEWgsbJDapAJQKDwNNP+gQE9gOgu5PAVyJnNi993sq7sBV+ktVJQpHyJVB2UXoBxNGHVaYuHwhnbywkt7gDXysbniPfTKp5HDHMoftFqg9lnqfpcBvYJvFgaYZCSSN0HBHSahnm1RHcCY+Ncv64yODoM7wChzlZg=
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export CONFIG=hydroblok/hbmall-config
- docker build -t $CONFIG:$COMMIT ./config
- docker tag $CONFIG:$COMMIT $CONFIG:$TAG
- docker push $CONFIG
- export REGISTRY=hydroblok/hbmall-registry
- docker build -t $REGISTRY:$COMMIT ./registry
- docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
- docker push $REGISTRY
- export GATEWAY=hydroblok/hbmall-gateway
- docker build -t $GATEWAY:$COMMIT ./gateway
- docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
- docker push $GATEWAY
- export AUTH_SERVICE=hydroblok/hbmall-auth-service
- docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
- docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
- docker push $AUTH_SERVICE
- export ACCOUNT_SERVICE=hydroblok/hbmall-account-service
- docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
- docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
- docker push $ACCOUNT_SERVICE
- export STATISTICS_SERVICE=hydroblok/hbmall-statistics-service
- docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
- docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
- docker push $STATISTICS_SERVICE
- export NOTIFICATION_SERVICE=hydroblok/hbmall-notification-service
- docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
- docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
- docker push $NOTIFICATION_SERVICE
- export MONITORING=hydroblok/hbmall-monitoring
- docker build -t $MONITORING:$COMMIT ./monitoring
- docker tag $MONITORING:$COMMIT $MONITORING:$TAG
- docker push $MONITORING
- export TURBINE=hydroblok/hbmall-turbine-stream-service
- docker build -t $TURBINE:$COMMIT ./turbine-stream-service
- docker tag $TURBINE:$COMMIT $TURBINE:$TAG
- docker push $TURBINE
- export MONGO_DB=hydroblok/hbmall-mongodb
- docker build -t $MONGO_DB:$COMMIT ./mongodb
- docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
- docker push $MONGO_DB
