sudo: required
services:
- docker
language: java
jdk: oraclejdk8

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: Qt4KXj3Pf3HhhreWl8NufJKBVz81a5QTlfoEJhUm1Wn2ZrZEFWymH5DMx84MDA6beTWNVsDWTqPmHl+WpMtv2yBvCOByWkiUOqFCO9Z/1meLHm2nxswPfbT4eJdr2Ksil+hP6vG62uzJfwbPrad9gKn8SO4mnLENz9QVUVfNS6jZ/hB/eJKN9IK8boorc+5xeGcHqPFGdWvdcaRavE0ugFW6frd0GswrV5DrEY22I6kyTUPlT0KLgkfwdSsVRq4XigJnXo0YHzcaOdHXZvPwa1Yo/nr8O2xhWLLQ4GlFU/LLu2FcPcS5VDHSbiGzz41jQs7Y66lYgNQeWYXvJbTXYmNbgeTH3OLhijS2oPXjw4wv5LehgMM39zMEFEIcwbHDFCCk5jBjiNTMWaoHs+xq2oPqjVm98n488cY5Wg3X40vo9yDxbUNA78fABLQnVYixCI0wDUGe0GpDnTSkVC+EMiOaEPE72JXMqbV7xyLXI3pqwJjN81dr/LTvgR7adTCtikFS5qRroWuR6ZndOgNNO80ng6cVHeyobFOtxhLAISE7zzPlV6B/LHyPx3ymg6juPT+fkOG89ZQe/a5I2goeFEWkSAtSEEJeGaOsxlesQiWO0qZG/P3AbV/Y7qszMYiANj2rdN9RwLqM3f0fz5lOWGr+3kBjznHtqErZ9J5PRRA= #DOCKER_USER
  - secure: Z/TVrVfLo2pwsiprgdYo9/frJBgnnoQuanDW8hPk1EAGu7YJxP7OT8VmhR9J0f9KGDlNDR0Ye6c4iHD1unatIbnS75NJWldLWLZX0kqitb9mfYDdCPUNEQOE7En9pVofY+Cd896duTGeyH+pvjaxB4EHOeXwsyWzi99amhuVLWOZ4BWSwF58hNyNhX/R3QVee3OWbfL1u3sR0IcDgbJIpQc5um0KYnxec/H7+hlaidVFTySDhWy3CzUMup0cJ3z+57jTyKV9U+3iAE7MF1c0ottL816gAJiect/hefxE8dV5lqPfdNKM2hPgcDRLR5SvLlp/QocDm6naXmjbQCr5vfLseO1fpiiGybr7hu3GX2AqHMHgvUQe4y451RhT1dNACTC+UZlDEgbP+VRcOS7+oxNxtoXlQb6nVsqRoq9b4OO5vO5ZcmvWzAzidmiSCo537R3WHSi+nzYKCzGP1yOnErpHZ+4M2DxPzEABvuSKO0E87pfcx56kERPLUgKJd+iLUTA4CH3DALXyEWgsbJDapAJQKDwNNP+gQE9gOgu5PAVyJnNi993sq7sBV+ktVJQpHyJVB2UXoBxNGHVaYuHwhnbywkt7gDXysbniPfTKp5HDHMoftFqg9lnqfpcBvYJvFgaYZCSSN0HBHSahnm1RHcCY+Ncv64yODoM7wChzlZg= #DOCKER_PASS
  - secure: YvlEqzgnRz8ZkiS1Ob0ePtTQXKynOnfTdGPai0wL+7Zp139XGVwulBYdDl/IPn+7dq/93g0MLe34EgeAa86kWeVabZ25ahc+gTh8cHLivFd90HAYMm7I25FhV9Q+5IQKLHLmZqM8j68d441xFNpAmXMkr6TJqickgXhSxC2yqhZEEoR1PzrlxX75+xoPPk9Sh8pZwXpsg1GdEefQQDyCLyTdAaxUAZaw2vN3FR1NfsrcmWjivLfJFscuBVOHEakwHnlahXo77EBiblkxJy7CI6xWGvgvIbk+8xOxnzpThV2V6Gf1t//rwwgIDswsy6WGEGhjV1t1Z9EtpnJD50kxr4P4aSDCn7V+zwPXjT5LtkDFhrFpDF066qxDtx/4w5rz5m8/qUERWQ+zEFVDxsiyo9zrOEvnwQiEOUGxnCyHbdA0msdmpoYf/xkk1wYez0shOj1YDfYIklRjTFu2D19A2zDoGkWqgXHfEZw45v1sZhp5hDFCnjd6Sk2QIuTYeET81ZHo4oBpsipq9yCy3TuhEV1AMJs+tlp9KZNw9T/FfYLxixO/F/rv4ulODCC1yHZuXG2TN3WooicC/a0pHwzw+jSbn47ZsDPw19B7AlltuJDus0i9DiRI4bB9z2x9JxUAfkB9DHZaOc5ObFFVd4Be7PHK5vkS88jvbRcS5SJxZbM= #SONAR_TOKEN
  - secure: unqY6awcdLMW7T400WoVwZR8AKBT1eZmhseU5XBUkgs1meUszTOO2bKeUUFmX3cwZYwz5X+/8tkeodg9a3zE5IQV64NFCtGn91/VIKpoWlWFEDYUuf3j0WRuO3gLOFy0XKCNdtjtQuDvZ0copotiDl1e2dC2KHhratRrmEXZSeitkh0Sgt6YqF8zzPjGf1qcigWcA7NsfvEnznmFiDObkmllgg6mUD2XiKg9INLdhYy1VxxHVBzBMvoyxs/aGUeOgdG6NjRLeRQn/G4kdujPcfAN5DiHOW7oUNb3XezdnK8OLgkr6KzZ9gDyoWO863OYoawYIGJFf1Y5jJ/BsJ1eqzf3FcRuY3jquDCC+LEIDnCfaaqrVPq2yYP5kNU3Fr54i/V/1Sn2R5ai/XsqJkL2sPMySZ6TI0JQiDlRrp5m95h0vc3jM+6L6lOr92f3uj8HXvcbXUCPRCtLR1G94FTbmZsXGcd1IsrQx13pyKkW2wC+tcLOHb3yHBF9MrUaKA7A1jAi6NSL6O42me6qPw65PUtHd3BuMj+0CHq1qyOPR9NZDR8gGRasaDQJjxOizAz65q9qQG6HI7Tu9sTX0g/zIwwqW7C5ZHAV9MEmFxRWA1SDn53afrFO2aRqzi9uisMeMxd8wDOy6yUH0bax9SJvcXWYA7hv5T/+65qMo29+5oQ= #HEROKU_API_TOKEN
addons:
  sonarcloud:
    organization: hydroblok
    token:
      secure: "$SONAR_TOKEN"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u $DOCKER_USER -p $DOCKER_PASS

#TAG
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

# CONFIG SERVICE
- export CONFIG=hydroblok/hbmall-config
- docker build -t $CONFIG:$COMMIT ./config
- docker tag $CONFIG:$COMMIT $CONFIG:$TAG
- docker push $CONFIG

# REGISTRY
- export REGISTRY=hydroblok/hbmall-registry
- docker build -t $REGISTRY:$COMMIT ./registry
- docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
- docker push $REGISTRY

# GATEWAY
- export GATEWAY=hydroblok/hbmall-gateway
- docker build -t $GATEWAY:$COMMIT ./gateway
- docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
- docker push $GATEWAY

# AUTH SERVICE
- export AUTH_SERVICE=hydroblok/hbmall-auth-service
- docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
- docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
- docker push $AUTH_SERVICE

# ACCOUNT SERVICE
- export ACCOUNT_SERVICE=hydroblok/hbmall-account-service
- docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
- docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
- docker push $ACCOUNT_SERVICE

# STATISTICS SERVICE
- export STATISTICS_SERVICE=hydroblok/hbmall-statistics-service
- docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
- docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
- docker push $STATISTICS_SERVICE

# NOTIFICATION_SERVICE
- export NOTIFICATION_SERVICE=hydroblok/hbmall-notification-service
- docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
- docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
- docker push $NOTIFICATION_SERVICE

# MONITORING
- export MONITORING=hydroblok/hbmall-monitoring
- docker build -t $MONITORING:$COMMIT ./monitoring
- docker tag $MONITORING:$COMMIT $MONITORING:$TAG
- docker push $MONITORING

# TURBINE STREAM SERVICE
- export TURBINE=hydroblok/hbmall-turbine-stream-service
- docker build -t $TURBINE:$COMMIT ./turbine-stream-service
- docker tag $TURBINE:$COMMIT $TURBINE:$TAG
- docker push $TURBINE

# MONGO DB
- export MONGO_DB=hydroblok/hbmall-mongodb
- docker build -t $MONGO_DB:$COMMIT ./mongodb
- docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
- docker push $MONGO_DB

deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: hydroblok