apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hbmall-config
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: hbmall-config
    spec:
      containers:
        - name: hbmall-config
          image: gcr.io/hbmall-252717/config:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hbmall-config
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: hbmall-config