apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: config
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: gcr.io/hbmall-252717/config:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /hydroblok/mall/
              port: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    app: config